spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_system_db
    username: postgres
    password: adminPostgres
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.authentication: DEBUG